spring:
    h2:
        console:
            enabled: true
            path: /homework
    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:mem:homework
        username: homework
        password: qwer1234

    jpa:
        show-sql: true
        properties:
            hibernate:
                format_sql: true
server:
    port: 8080
